### PR TITLE
fix(layout): bouncing preventing add

### LINKED ISSUE #183: Layout: fix auth containers
Prevent container bounces on Auth layouts

### PR DESCRIPTION
**Pull request by 32penkin**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/kittenTricks/blob/master/CONTRIBUTING.md) guide.

Closes #183

### CODE REVIEW

File: src/components/common/scrollableAvoidKeyboard.component.tsx [hunk 1]
```diff
@@ -19,6 +19,7 @@ class ScrollableAvoidKeyboardComponent extends React.Component<ScrollableAvoidKe
     return (
       <KeyboardAwareScrollView
         {...restProps}
+        bounces={false}
```
Comment (artyorsh) [inline src/components/common/scrollableAvoidKeyboard.component.tsx:21]: You should add more restricting props and give a possibility to override them
[See an example](https://github.com/akveo/kittenTricks/blob/master/src/components/common/containerView.component.tsx#L19)

**Review by artyorsh — CHANGES_REQUESTED** [review]

File: src/components/common/scrollableAvoidKeyboard.component.tsx (hunk 1 above)
Comment (32penkin) [reply src/components/common/scrollableAvoidKeyboard.component.tsx:21]: Done

**Review by artyorsh — APPROVED** [review]
